/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author aaron
 */
import BO.ProductoBO;
import DAO.*;
import com.sun.rowset.CachedRowSetImpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.*;

public class frmProductos extends javax.swing.JFrame {
    //variables de la clase
    DefaultTableModel modeloProducto;
    boolean estado = false;
    /**
     * Creates new form Productos
     */
    public frmProductos() {        
        this.bindGrid();
        initComponents();
        this.desactivarCampos();
        this.cboAlmacen.removeAllItems();
        this.cboCategoria.removeAllItems();
        
        this.cboAlmacen.addItem("1");
        this.cboAlmacen.addItem("2");
        this.cboAlmacen.addItem("3");
        
        this.cboCategoria.addItem("1");
        this.cboCategoria.addItem("2");
        this.cboCategoria.addItem("3");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgProducto = new javax.swing.JTable();
        pnlDatosP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JEditorPane();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioU = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        spStock = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboAlmacen = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(jPanel1);
        jLabel1.setText("Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(405, 405, 405))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        dgProducto.setModel(modeloProducto);
        dgProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dgProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgProducto);
        dgProducto.getAccessibleContext().setAccessibleName("dgProductos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Datos del Producto ");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Descripcion");

        jScrollPane2.setViewportView(txtDescripcion);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Precio unitario");

        txtPrecioU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioUActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("Precio mayoreo");

        txtPrecioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioMActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("Stock");

        btnAgregar.setText("Nuevo");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditarMouseClicked(evt);
            }
        });

        btnBuscar.setText("Buscar");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel8.setText("ID");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText("Cantidad");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setText("Almacen");

        cboAlmacen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel11.setText("Categoría");

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlDatosPLayout = new javax.swing.GroupLayout(pnlDatosP);
        pnlDatosP.setLayout(pnlDatosPLayout);
        pnlDatosPLayout.setHorizontalGroup(
            pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPLayout.createSequentialGroup()
                .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(pnlDatosPLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(spStock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cboAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        pnlDatosPLayout.setVerticalGroup(
            pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosPLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosPLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosPLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(2, 2, 2)
                                .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDatosPLayout.createSequentialGroup()
                                        .addComponent(btnAgregar)
                                        .addGap(13, 13, 13)
                                        .addComponent(btnEliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btneditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar))
                                    .addGroup(pnlDatosPLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))))
                            .addGroup(pnlDatosPLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDatosP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pnlDatosP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioUActionPerformed

    private void txtPrecioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioMActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        this.guardar();
        this.limpiarDatos();        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void dgProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgProductoMouseClicked
        // TODO add your handling code here:
        int row = this.dgProducto.getSelectedRow();
        
        String[] datos = new String[9];
        datos[0] = this.dgProducto.getModel().getValueAt(row, 0).toString();
        datos[1] = this.dgProducto.getModel().getValueAt(row, 1).toString();
        datos[2] = this.dgProducto.getModel().getValueAt(row, 2).toString();
        datos[3] = this.dgProducto.getModel().getValueAt(row, 3).toString();
        datos[4] = this.dgProducto.getModel().getValueAt(row, 4).toString();
        datos[5] = this.dgProducto.getModel().getValueAt(row, 5).toString();
        datos[6] = this.dgProducto.getModel().getValueAt(row, 6).toString();
        datos[7] = this.dgProducto.getModel().getValueAt(row, 7).toString();
        datos[8] = this.dgProducto.getModel().getValueAt(row, 8).toString();
        
        
        this.llenarDatos(datos);
    }//GEN-LAST:event_dgProductoMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            // TODO add your handling code here:
            this.elimianar();
        } catch (SQLException ex) {
            Logger.getLogger(frmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btneditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditarMouseClicked
        try {
            // TODO add your handling code here:
            this.editar();
        } catch (SQLException ex) {
            Logger.getLogger(frmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditarMouseClicked
    
    private void llenarDatos(String[] datos){
        this.txtID.setText(datos[0]);
        this.txtNombre.setText(datos[1]);
        this.txtDescripcion.setText(datos[2]);
        this.txtPrecioM.setText(datos[3]);
        this.txtPrecioU.setText(datos[4]);
        this.spStock.setValue(Integer.parseInt(datos[6]));
        this.txtCantidad.setText(datos[5]);
        this.cboAlmacen.setSelectedItem(datos[8]);
        this.cboCategoria.setSelectedItem(datos[7]);
        
    }
    private void limpiarDatos(){
        this.txtID.setText(null);
        this.txtDescripcion.setText(null);
        this.txtNombre.setText(null);
        this.txtPrecioM.setText(null);
        this.txtPrecioU.setText(null);
        this.spStock.setValue(0);        
    }
    
    private boolean desactivarCampos(){
        this.txtID.setEnabled(false);
        this.txtDescripcion.setEnabled(false);
        this.txtNombre.setEnabled(false);
        this.txtPrecioM.setEnabled(false);
        this.txtPrecioU.setEnabled(false);
        this.spStock.setEnabled(false); 
        this.cboAlmacen.setEnabled(false);
        this.cboCategoria.setEnabled(false);
        this.txtCantidad.setEnabled(false);
        
        return false;
    }
    
     private boolean activarCampos(){
        this.txtDescripcion.setEnabled(true);
        this.txtNombre.setEnabled(true);
        this.txtPrecioM.setEnabled(true);
        this.txtPrecioU.setEnabled(true);
        this.spStock.setEnabled(true); 
        this.cboAlmacen.setEnabled(true);
        this.cboCategoria.setEnabled(true);
        this.txtCantidad.setEnabled(true);
        
        return true;
    }
    private void bindGrid(){
        
        try {
            modeloProducto = new DefaultTableModel(null, this.getColumnas());
            ProductoDAO data = new ProductoDAO();
            CachedRowSetImpl crs = data.mostrar();
            Object datos[] = new Object[9];
            
            
                while (crs.next()){
                    for (int i = 0; i < 9; i++){
                        datos[i] = crs.getObject(i+1);
                    }   
                    modeloProducto.addRow(datos);
                }
            
            
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(frmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private String[] getColumnas(){
        String columns[] = new String[]{"ID", "Nombre", "Descripcion", "Precio Mayoreo", "Precio Unitario", "Cantidad", "Stock", "Categoria", "Almacen"};
        return columns;
    }
    /**                      
     * ---métodos ABC---
     */
    
    private void guardar(){
        
        
        this.activarCampos();
        
        if (estado == false){
            estado = this.activarCampos();
                        
            this.btnAgregar.setText("Guardar");
            this.btnBuscar.setVisible(false);
            this.btnEliminar.setVisible(false);
            this.btneditar.setVisible(false);
            this.btnBuscar.setVisible(false);
            
        }
        else{
            
            ProductoBO oProducto = new ProductoBO();
            oProducto.setNombre(this.txtNombre.getText());
            oProducto.setDescripcion(this.txtDescripcion.getText());
            oProducto.setPrecioMayoreo(Double.parseDouble(this.txtPrecioM.getText()));
            oProducto.setPrecioUnitario(Double.parseDouble(this.txtPrecioU.getText()));
            oProducto.setStock((int) this.spStock.getValue());
            oProducto.setCantidad(Integer.parseInt(this.txtCantidad.getText()));
            oProducto.setIDAlmacen(Integer.parseInt(this.cboAlmacen.getSelectedItem().toString()));
            oProducto.setIDCategoria(Integer.parseInt(this.cboCategoria.getSelectedItem().toString()));
            
            
            
        
            ProductoDAO data = new ProductoDAO();
            int correcto = data.guardar(oProducto);
        
            if (correcto > 0){
                JOptionPane.showMessageDialog(null, "Operación realizada con éxito");
                estado = this.desactivarCampos();
                this.limpiarDatos();
                this.btnAgregar.setText("Nuevo");
                this.btnBuscar.setVisible(true);
                this.btnEliminar.setVisible(true);
                this.btneditar.setVisible(true);
                this.btnBuscar.setVisible(true);
                
                this.bindGrid();
                this.dgProducto.setModel(modeloProducto);
            }
            else{
                JOptionPane.showMessageDialog(null, "Error");
                estado = this.desactivarCampos();
                this.btnAgregar.setText("Nuevo");
                this.btnBuscar.setVisible(true);
                this.btnEliminar.setVisible(true);
                this.btneditar.setVisible(true);
                this.btnBuscar.setVisible(true);

            } 
        }
        
        
                
    }
    
    private void elimianar() throws SQLException {
        int correcto = 0;
        ProductoBO oProducto = new ProductoBO();
        ProductoDAO data = new ProductoDAO();
        oProducto.setID(Integer.parseInt(this.txtID.getText()));
        
        correcto = data.eliminar(oProducto);
        
        if (correcto > 0){
            JOptionPane.showMessageDialog(null, "Operación relizada con éxito");
            this.limpiarDatos();
            this.bindGrid();
            this.dgProducto.setModel(modeloProducto);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Error");
        }
        
    }
    
    private void editar() throws SQLException{
        
        if (estado == false){
            estado = this.activarCampos();
                        
            this.btnAgregar.setVisible(false);
            this.btnBuscar.setVisible(false);
            this.btnEliminar.setVisible(false);
            this.btneditar.setText("Guardar");
            this.btnBuscar.setVisible(false);
            
        }
        else{
            int correcto = 0;
            ProductoBO oProducto = new ProductoBO();
            ProductoDAO data = new ProductoDAO();
        
            oProducto.setID(Integer.parseInt(this.txtID.getText()));        
            oProducto.setNombre(this.txtNombre.getText());
            oProducto.setDescripcion(this.txtDescripcion.getText());
            oProducto.setPrecioMayoreo(Double.parseDouble(this.txtPrecioM.getText()));
            oProducto.setPrecioUnitario(Double.parseDouble(this.txtPrecioU.getText()));
            oProducto.setStock((int) this.spStock.getValue());
            oProducto.setCantidad(Integer.parseInt(this.txtCantidad.getText()));
            oProducto.setIDAlmacen(Integer.parseInt(this.cboAlmacen.getSelectedItem().toString()));
            oProducto.setIDCategoria(Integer.parseInt(this.cboCategoria.getSelectedItem().toString()));
        
            correcto = data.editar(oProducto);
        
            if (correcto > 0){
                JOptionPane.showMessageDialog(null, "Operación relizada con éxito");
                
                estado = this.desactivarCampos();
                
                this.btnAgregar.setVisible(true);
                this.btnBuscar.setVisible(true);
                this.btnEliminar.setVisible(true);
                this.btneditar.setText("Editar");
                this.btnBuscar.setVisible(true);
                
                this.limpiarDatos();
                this.bindGrid();
                this.dgProducto.setModel(modeloProducto);
            }
            else{
                 JOptionPane.showMessageDialog(null, "Error");
            }
        }
        
        
        
    }
    
    /**                      
     * ---FIN métodos ABC---
     */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btneditar;
    private javax.swing.JComboBox<String> cboAlmacen;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JTable dgProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlDatosP;
    private javax.swing.JSpinner spStock;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JEditorPane txtDescripcion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioM;
    private javax.swing.JTextField txtPrecioU;
    // End of variables declaration//GEN-END:variables
}
